# Lambda

In [ ]:
def square(x):
    return x*x

In [3]:
square(3)

9

In [12]:
square_lambda = lambda x : x*x

In [13]:
square_lambda(3)

9

In [14]:
square_lambda = lambda x : print(x+x, "hello")

In [15]:
add_with_lambda = lambda x, y, z : x + y + z

In [17]:
add_with_lambda(1, 2,3)

6

# Sort

In [18]:
a = [1,2,110, -3, 5, 6, 90, 78]

In [19]:
a.sort()

In [20]:
a

[-3, 1, 2, 5, 6, 78, 90, 110]

In [29]:
a = [1,2,110, -3, 5, 6, 90, 78]

In [30]:
a.sort(reverse=True)

In [31]:
a

[110, 90, 78, 6, 5, 2, 1, -3]

# Sorted

In [21]:
a = [1,2,110, -3, 5, 6, 90, 78]

In [22]:
sorted_a = sorted(a)

In [23]:
a

[1, 2, 110, -3, 5, 6, 90, 78]

In [24]:
sorted_a

[-3, 1, 2, 5, 6, 78, 90, 110]

# Using key= in both sort and sorted

In [25]:
words = ["apple", "kiwi", "banana"]
# apple - 5
# kiwi - 4
# banana - 6

# kiwi, apple, banana

In [26]:
words.sort(key=len)

In [27]:
words

['kiwi', 'apple', 'banana']

In [ ]:
words = ["apple", "kiwi", "banana"]
print(sorted(words, key=len))

['kiwi', 'apple', 'banana']


In [ ]:
words = ["apple", "kiwi", "banana"]
print(sorted(words, key=lambda x : x[-1]))

['banana', 'apple', 'kiwi']


In [33]:
def get_last_char(x):
    return x[-1]

In [36]:
words = ["apple", "kiwi", "banana"]
# apple - e
# kiwi - i
# banana - a

print(sorted(words, key=get_last_char))

['banana', 'apple', 'kiwi']


In [37]:
print(sorted(words, key=get_last_char, reverse=True))

['kiwi', 'apple', 'banana']


In [47]:
a_dict = {
    1 : "hello",
    100 : "bye",
    2 : "How are you!"
}

In [43]:
print(sorted(a_dict))

[1, 2, 100]


In [42]:
for i in a_dict:
    print(i)

1
100
2


In [ ]:
print(sorted(a_dict.items())) # iterations

[(1, 'hello'), (2, 'How are you!'), (100, 'bye')]


In [45]:
for k, v in a_dict.items():
    print(k)

1
100
2


# map()

In [49]:
# synatx map(fucntion, iterable)

In [50]:
square = lambda x : x*x

In [ ]:
nums = list(range(0,11))
# nums = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [57]:
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [55]:
result = list(map(square, nums))

In [56]:
print(result)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [58]:
# map will apply a function to all items in an iterable

In [73]:
add_lambda = lambda item : item[0] + item[1]

In [74]:
a = [(1,2),(3,4),(5,6),(7,8)]

In [75]:
list(map(add_lambda, a))

[3, 7, 11, 15]

# zip

In [87]:
names = ["monal", "gagan", 1]
scores = [10, 100]

In [88]:
list(zip(names, scores))

[('monal', 10), ('gagan', 100)]

In [89]:
for i in zip(names, scores):
    print(i)

# packing

('monal', 10)
('gagan', 100)


In [91]:
dict(zip(names, scores))

{'monal': 10, 'gagan': 100}

# unpacking

In [94]:
nums = [1,2,3]

In [95]:
print(*nums)

1 2 3


In [96]:
def add(a,b,c):
    print(a+b+c)

In [ ]:
add(*nums)
# 1,2,3

6


In [99]:
for i in zip(names, scores):
    print(*i)

# packing

monal 10
gagan 100


In [102]:
def zip_files(*files):
    print("Zipping:", files)

all_files = [1,2,3]


In [103]:
zip_files(*all_files)

Zipping: (1, 2, 3)


In [104]:
nums = [(1,"monal"),(2,"hello"),(3, 100)]

In [105]:
print(*nums)

(1, 'monal') (2, 'hello') (3, 100)


In [106]:
names, scores = zip(*nums)
print(names)
print(scores)

(1, 2, 3)
('monal', 'hello', 100)


# list comprehension

In [109]:
# short expressive way to generate a new list or filter a list

In [ ]:
nums = [1,1,1,1,1,2,2,3,4,1,1,11,234,1]

In [111]:
# Syntax : [expression for item in iterable if condition]

In [112]:
# ps : keep all the ones

In [113]:
new_res = []
for i in nums:
    if i == 1:
        new_res.append(i)
print(new_res)

[1, 1, 1, 1, 1, 1, 1, 1]


In [114]:
new_res = [i for i in nums if i==1]

In [115]:
print(new_res)

[1, 1, 1, 1, 1, 1, 1, 1]


In [116]:
# ps : square of numbers

In [118]:
new_res = []
for i in nums:
    new_res.append(i*i)
print(new_res)

[1, 1, 1, 1, 1, 4, 4, 9, 16, 1, 1, 121, 54756, 1]


In [119]:
new_res = [i*i for i in nums]

In [120]:
new_res

[1, 1, 1, 1, 1, 4, 4, 9, 16, 1, 1, 121, 54756, 1]

In [ ]:
nums = [1,2,3]

# p.s. : if the number is even, then perform the square and output should be in list

In [121]:
ans=[i*i for i in nums if i%2==0]

In [122]:
print(ans)

[4, 4, 16, 54756]


# Dict comprehension

In [126]:
# {key_expression : value_expression for item in iterable if condition}

In [127]:
names = ["monal", "gagan", "hello"]
scores = [10, 100, -100]

In [128]:
result = {name.capitalize() : score+100 for name, score in zip(names, scores)}

In [129]:
print(result)

{'Monal': 110, 'Gagan': 200, 'Hello': 0}


# Numpy

In [131]:
# !pip install numpy

In [134]:
import numpy as np
import time

In [151]:
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()
time_taken_p = end_t-start_t
print(f"Time taken : {time_taken_p}")

Time taken : 4.444943189620972


In [152]:

a = list(range(100000000))
b = list(range(100000000))
a = np.array(a)
b = np.array(b)

start_t = time.time()
c = a + b
end_t = time.time()
time_taken_n = end_t-start_t
print(f"Time taken : {time_taken_n}")

Time taken : 0.6770763397216797


In [153]:
time_taken_p/time_taken_n

6.564906981461084

# 1. np.array()

In [155]:
array_n1 = np.array([1,2,3])

In [159]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [160]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(type(array_n2))
print(type(array_n2[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [162]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [166]:
array_n2 = np.array([1,2,"3"], dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start, stop, step)

In [169]:
print(np.arange(5))

print(np.arange(1, 10, 2))

np_arange = np.arange(1, 10, 2)
print(type(np_arange))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


# np.linspace(start, stop, num=x)

In [174]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [175]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [182]:
npz_1 = np.zeros(5)

In [183]:
npz_1.ndim

1

In [185]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [186]:
npz_2.ndim

2

In [187]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [188]:
npz_3.ndim

3