# np.zeros()

In [2]:
### np.zeros()

import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros((5, 5)).shape

(5, 5)

In [7]:
np.zeros((5, 5)).ndim

2

# np.ones()

In [9]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.ones((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# np.full()

In [ ]:
# list of size 10, all filled with value 5

In [11]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [14]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)

In [27]:
np.eye(6, 6, 4)

array([[0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# np.empty(shape)

In [29]:
a = np.full((5,5), 0)

In [30]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# np.empty(shape)

In [31]:
np.empty((5,5))

array([[4.67296746e-307, 1.69121096e-306, 1.24610859e-306,
        1.33511562e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307],
       [9.34598925e-307, 1.42418715e-306, 1.95819401e-306,
        1.37961370e-306, 6.23054633e-307],
       [9.34598926e-307, 6.89804132e-307, 9.34598926e-307,
        8.01091099e-307, 1.24610927e-306],
       [2.22522597e-306, 8.90109671e-307, 1.24610994e-306,
        8.34445137e-308, 3.91792476e-317]])

In [33]:
np.empty((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [34]:
np.empty((5,5), dtype=int)

array([[23925768161198179, 32370111954616435, 30399722694049884,
        30962698416881756, 30962724186030185],
       [25895916907069540, 25896118771056716, 28429470870863987,
        27866439313522733, 28429415035764843],
       [28429402150535283, 31525639780892770, 33214455279779961,
        31244151918821477, 25896127360729202],
       [28429402152435824, 26740517931057270, 28429402152435824,
        27584955746091126, 30399726988689525],
       [34058953224355941, 28148004483825764, 30399731283918943,
        12948278431776879,           7929968]])

In [35]:
import time

perf_counter() is used to get high-resolution time counter.

In [37]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

4.750000016429112e-05


In [38]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

6.639999992330559e-05


# np.random.rand(shape)

In [44]:
np.random.rand(5,5)

array([[0.42540496, 0.3247875 , 0.14292218, 0.13301403, 0.69823461],
       [0.89985142, 0.98758595, 0.90612365, 0.76529655, 0.05254269],
       [0.68723942, 0.89674611, 0.31236049, 0.4415451 , 0.07021806],
       [0.97549033, 0.45984887, 0.99832344, 0.53776506, 0.56226694],
       [0.60178635, 0.19856975, 0.02966449, 0.11872842, 0.04783561]])

In [69]:
a = np.random.rand(10)*10

In [70]:
a = a.tolist()

In [71]:
a

[8.2185276522925,
 2.876617075657445,
 3.6536418353894886,
 8.310386900359886,
 2.1760829172418705,
 9.976333321080947,
 0.3040324558416341,
 0.867267265889714,
 6.45601498849998,
 2.3718434807476116]

In [72]:
a = [int(i) for i in a]

In [73]:
a

[8, 2, 3, 8, 2, 9, 0, 0, 6, 2]

In [68]:
a

[6, 4, 7, 6, 4, 2, 4, 6, 7, 1]

In [84]:
np.random.randint(1, 11, 10)

array([ 5,  5, 10,  9,  8,  5,  7,  8,  4,  2], dtype=int32)

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

# Answers


A 1D array of numbers from 0 to 9
```bash
arr1 = np.arange(10)
print(arr1)
```

A 3x3 matrix of all 5s
```bash
arr2 = np.full((3, 3), 5)
print(arr2)
```

A 4x4 identity matrix
```bash
arr3 = np.eye(4)
print(arr3)
```

10 evenly spaced numbers between 1 and 100
```bash
arr4 = np.linspace(1, 100, 10)
print(arr4)
```

A 2x2 array with random values between 0 and 1
```bash
arr5 = np.random.rand(2, 2)
print(arr5)
```

# numpy attributes

In [85]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [86]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [87]:
arr.shape

(2, 3)

In [88]:
arr.ndim

2

In [89]:
arr.dtype

dtype('int64')

# ndarray.itemsize

In [ ]:
arr.itemsize # size in bytes of one element

8

In [ ]:
# 1 gb --> 1024 mb
# 1 mb --> 1024 kb
# 1 kb --> 1024 bytes
# 1 byte --> 8 bit

# Java
# - int --> 4 bytes
# - float --> 4 bytes
# - char --> 1 byte

In [ ]:
# import sys

# print("Size of int:", sys.getsizeof(int()))  # Integer
# print("Size of float:", sys.getsizeof(float()))  # Floating-point number
# print("Size of str:", sys.getsizeof(str()))  # String
# print("Size of list:", sys.getsizeof(list()))  # List
# print("Size of tuple:", sys.getsizeof(tuple()))  # Tuple
# print("Size of dict:", sys.getsizeof(dict()))  # Dictionary
# print("Size of set:", sys.getsizeof(set()))  # Set


Size of int: 28
Size of float: 24
Size of str: 41
Size of list: 56
Size of tuple: 40
Size of dict: 64
Size of set: 216


In [93]:
arr.nbytes # total number of bytes consumed by the array

48

In [94]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [95]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
a = np.array([[1,2,3], [4,5,6]])

In [101]:
print(a.shape)
print(a.T.shape)

(2, 3)
(3, 2)


In [103]:
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [104]:
z = np.full((3,5),3)
print(z)
z = z.T
print(z)


[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


# indexing and slicing

In [105]:
arr = np.array([10,20,30,40,50,60])

In [107]:
print(arr[0])
print(arr[-1])

10
60


In [111]:
print(arr[1:4])
print(arr[:3])
print(arr[0:3])

[20 30 40]
[10 20 30]
[10 20 30]


In [113]:
print(arr[::2]) # (start with 0 and step size 2)


[10 30 50]


In [114]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [118]:
print(mat[0,1])
print(mat[1])
print(mat[:,2])
print(mat[:,-1])

2
[4 5 6]
[3 6 9]
[3 6 9]


In [119]:
print(mat[0:2,1:])

[[2 3]
 [5 6]]


In [120]:
arr_temp = np.array([1,2,3,4,5,6,7,8,9])

In [121]:
arr_temp[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [123]:
# [[9, 8, 7],
# [6, 5, 4],
# [3, 2, 1]]

print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [126]:
arr = np.array([5, 10, 15, 20, 25])

In [127]:
arr>10

array([False, False,  True,  True,  True])

In [129]:
print(arr[arr>10]) # boolean indexing

[15 20 25]


In [130]:
indx = [0,3,4]
arr[indx]

array([ 5, 20, 25])

In [131]:
arr[0] = 50
print(arr)

[50 10 15 20 25]


# indexing with np.where()

In [132]:
arr = np.array([10, 15, 20, 25, 30])

In [133]:
idx = np.where(arr>20)
print(idx)

(array([3, 4]),)


In [134]:
print(arr[idx])

[25 30]


# array reshaping and resizing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [138]:
arr.shape

(6,)

In [139]:
reshaped = arr.reshape(2,3)

In [140]:
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [151]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [152]:
reshaped = arr.reshape(3,-1)

In [153]:
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [144]:
reshaped.shape

(3, 4)

In [154]:
a = np.array([[1, 2], [3, 4]])

In [155]:
b = a.flatten()

In [156]:
b

array([1, 2, 3, 4])

In [157]:
a = np.array([1, 2, 3, 4])

In [ ]:
a.resize((2,3))

In [159]:
print(a)

[[1 2 3]
 [4 0 0]]


In [160]:
a = np.array([1, 2, 3, 4])

In [161]:
a.resize((2,1))

In [162]:
print(a)

[[1]
 [2]]


In [163]:
# reshape will throw error if values are insufficient
# resize will truncate or padd with zeros

In [ ]:
12, (4,5)--> 20 --> reshape will throw error
12, (4,5) --> 20 --> resize, it will pad extra element with 0

12-> 8--> 0

In [167]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)

(2, 3, 1)


In [166]:
a = np.array([[1],[2],[3]])
print(a.shape)

(3, 1)


In [ ]:
a = np.array([[[1],[2],[3]]])
print(a.shape)

(1, 3, 1)


In [172]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a)
print(b.shape)
print(b)

(2, 3, 1)
(2, 3)
[[1 2 3]
 [1 2 3]]


In [170]:
b = np.squeeze(a)
print(b.shape)
print(b)

(3,)
[1 2 3]


In [177]:
a = np.array([[[1],[2],[3]]])
print(a.shape)
b = np.squeeze(a, axis=0)
print(b.shape)
print(b)

(1, 3, 1)
(3, 1)
[[1]
 [2]
 [3]]


In [171]:
b = np.array([b])
print(b)

[[1 2 3]]


In [182]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [183]:
print(np.sum(a, axis=0)) # rows wise

[3 6 9]


In [ ]:
print(np.sum(a, axis=1)) # column wise

[6 6 6]
